### ISSUE TITLE
FINALE TO-DO LIST

### ISSUE THREAD

**Issue by ZephyrRaine** [ZephyrRaine/LD38#14]
***IMPORTANT STUFF***
- [ ] Integrate finale scene
- [ ] Add Beta Testers names
- [ ] Integrate last screen => BROWNIE COVE HOTEL <=
- [ ] Integrate and adjust audio
- [ ] Randomize custom guests order a bit

***POLISH STUFF***
- [ ] Kind of a menu
- [ ] Actual writing in the book
- [ ] Changing character name speaking color
- [ ] Changing character name speaking scale
- [ ] Notifications (drawer, telephone, message, bell)
- [ ] Animate head
- [ ] Animate drawer

**Comment by ZephyrRaine** [comment]
Yeah I agree on this whole "things happening if you don't answer to people" that'll help with being able to have people keep reading and stuff, I thought like maybe if you don't answer/help them like your chaos value would increase and maybe the hotel would start look chaotic? (if we push it far enough like maybe a whole story branch where all requests from three contact mediums get more and more fucked up)

I dunno let me think.
